name: Build main

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run build
