name: Build dev
on:
  push:
    branches: [ dev ]
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build