name: Build dev
on:
  push:
    branches: [ dev ]
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: refs/heads/dev
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: clean cache
        run: npm cache clean --force
      - name: install
        run: npm install
      - name: Clean install
        run: npm ci
      - name: Build next
        run: npm run build:debug